name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
    - name: Set up Python 3.6
    - uses: actions/setup-python@v3
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: make install
      
    - name: Run Lint
      run: make lint
      
    - name: Run distcheck
      run: make test
